# Airthematic Operation in Array

In [1]:
import numpy as np 
var =np.array([1,2,3,4])
varadd = var+2
print(varadd)

[3 4 5 6]


In [2]:
var1 =np.array([1,2,3,4])
var2 =np.array([1,2,3,4])
varadd =var1+var2
print(varadd)

[2 4 6 8]


In [3]:
var1 =np.array([1,2,3,4])
var2 =np.array([1,2,3,4])
varadd =var1-var2
print(varadd)

[0 0 0 0]


In [4]:
var1 =np.array([1,2,3,4])
var2 =np.array([1,2,3,4])
varadd =var1*var2
print(varadd)

[ 1  4  9 16]


In [7]:
vvar1 =np.array([1,2,3,4])
var2 =np.array([1,2,3,4])
varadd =var1/var2
print(varadd)

[1. 1. 1. 1.]


In [8]:
var1 =np.array([1,2,3,4])
var2 =np.array([1,2,3,4])
varadd =var1%var2
print(varadd)

[0 0 0 0]


use numpy function for perform the operation

add()

In [9]:
var1 =np.array([1,2,3,4])
var2 =np.array([1,2,3,4])
varadd =np.add(var1,var2)
print(varadd)

[2 4 6 8]


# 2D Array

In [10]:
var1 =np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
var2 =np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
varadd = var1+var2
print(varadd)

[[2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]]


In [13]:
var1 =np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
var2 =np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
varadd = np.multiply(var1,var2)
print(varadd)

[[ 1  4  9 16]
 [ 1  4  9 16]
 [ 1  4  9 16]]


recipocal

In [14]:
var1 =np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
varreci = np.reciprocal(var1)
print(varreci)



[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]


# Other Important Functions

In [24]:
a = np.array([2,3,4,5,1,0,6,6])
minimun = np.min(a) #min
maximum = np.max(a) #max
print(minimun)
print(maximum)
print(np.argmin(a))
print(np.argmax(a))
# print(np.argpartition(a))
print(np.argsort(a))

0
6
5
6
[5 4 0 1 2 3 6 7]


In [30]:
a2 = np.array([[1,2,3,4],[3,5,2,6]])
print(np.min(a2,axis=0 )) #give the minimun value according to the colum
print(np.min(a2,axis=1 )) #give the minimun value according to the row

[1 2 2 4]
[1 2]


squart

In [32]:
a = np.array([2,3,4,5,1,0,6,6])
print(np.sqrt(a)) #square root of array element
print(np.square(a))  #square  of array element

[1.41421356 1.73205081 2.         2.23606798 1.         0.
 2.44948974 2.44948974]
[ 4  9 16 25  1  0 36 36]


sin , cos ,tan

In [35]:
var = np.array([1,2,3])
print(np.sin(var))
print(np.cos(var))
print(np.tan(var))
print(np.sinh(var))
print(np.cosh(var))
print(np.tanh(var))

[-0.98803162  0.90929743  0.14112001]
[ 0.15425145 -0.41614684 -0.9899925 ]
[-6.4053312  -2.18503986 -0.14254654]
[5.34323729e+12 3.62686041e+00 1.00178749e+01]
[5.34323729e+12 3.76219569e+00 1.00676620e+01]
[1.         0.96402758 0.99505475]


cumsum , cumproduct

In [38]:
var = np.array([1,2,3 ,4])
print(np.cumsum(var))
print(np.cumprod(var))
print(np.cumproduct(var))

[ 1  3  6 10]
[ 1  2  6 24]
[ 1  2  6 24]
