Array

In [10]:
import numpy as np

x= [1,2,3,4]
y =np.array(x)
print(y)
y
x
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [14]:
ar = np.array([[1,2,3],[3,4,5]])
print(ar)
ar.ndim

[[1 2 3]
 [3 4 5]]


2

In [17]:
ar2 = np.array([[[1,2,2,3],[34,5,6,7]]])
print(ar2.ndim)
ar2

3


array([[[ 1,  2,  2,  3],
        [34,  5,  6,  7]]])

In [20]:
arn =np.array([3,2,2,45,5],ndmin=10)
print(arn)
arn.ndim

[[[[[[[[[[ 3  2  2 45  5]]]]]]]]]]


10

In [9]:

l=[]

for i in range(5):
    n = int(input("ENter "))
    l.append(n)
print(l)

['2', '3', '4', '5', '6']
