# for the broadcasting rule


1 : In two array should be the one common dimaension 

2 : Or atlest one 1 in dimension of any one of array



ex: v1(3,1) +v2(1,3)

ex : v1(2,1) +v2(2,3)

In [7]:
import numpy as np

var1  = np.array([1,24,5])
var2  = np.array([1,24,5]).reshape(3,1)
print(var1+var2)

[[ 2 25  6]
 [25 48 29]
 [ 6 29 10]]


In [10]:
x= np.array([[1],[2]])
print(x.shape)
y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()
print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]
