# Shuffle

Shuffle mei element ki position change karta hai

In [13]:
import numpy as np  
var = np.array([1,2,3,4,5])
print(var)
np.random.shuffle(var)
print(var)


[1 2 3 4 5]
[2 1 4 5 3]


In [16]:
var1 = np.array([1,2,3,4,43,2,7,4])
x= np.unique(var1 ,return_index=True ,return_counts=True)
print(x)

(array([ 1,  2,  3,  4,  7, 43]), array([0, 1, 2, 3, 6, 4], dtype=int64), array([1, 2, 1, 2, 1, 1], dtype=int64))


Resize

In [18]:
var2 = np.array([1,2,3,4,5,6])
y= np.resize(var2 , (2,3))
print(y)

[[1 2 3]
 [4 5 6]]


Flatten

In [29]:
var2 = np.array([1,2,3,4,5,6])
y= np.resize(var2 , (3,2))
print(y)
print()
print("Flatten Order ",y.flatten(order="F"))
print("Ravel : " , np.ravel(y))
print("Ravel : " , np.ravel(y,order="F"))

[[1 2]
 [3 4]
 [5 6]]

Flatten Order  [1 3 5 2 4 6]
Ravel :  [1 2 3 4 5 6]
Ravel :  [1 3 5 2 4 6]
