# Indexing 

In [46]:
import numpy as np
var = np.array([3,4,5,6])
print(var[2])
print(var[-1])
print(var[-3])

5
6
4


In [47]:
var2 =np.array([[1,3,4],[4,5,6]])
print(var2.ndim)
print(var2)

print(var2[0,1])
print(var2[0,0])

2
[[1 3 4]
 [4 5 6]]
3
1


In [48]:
var3 =np.array([[[1,3],[2,7]]])
print(var3.ndim)

print(var3[0,1,1])

3
7


# slicing

In [49]:

v = np.array([1,3,5,6,7,44,33,55,63,332])
#             0,1,2,3,4,5 ,6, 7 ,8, 9
print(v[2:8])
print(v[-7:-2])
print(v[4:])
print(v[:5])
print(v[::2]) #double jump fetch the data
print(v[1:8:3])
print(len(v)) #length


[ 5  6  7 44 33 55]
[ 6  7 44 33 55]
[  7  44  33  55  63 332]
[1 3 5 6 7]
[ 1  5  7 33 63]
[ 3  7 55]
10


for 2D array slicing