# Insert  

In [24]:
import numpy as np 
var = np.array([1,2,3,4])
print(var)
v1 =np.insert(var , len(var) ,6)
v =np.insert(var , 3 ,33)
v= np.insert(var , (1,2,3), 9)
v= np.append(var ,22)
print(v)

[1 2 3 4]
[ 1  2  3  4 22]


In [33]:
var1 =np.array([[1,2],[3,4]])
v1 = np.insert(var1 , 2 ,6 ,axis=0)
v2 = np.insert(var1 , 2 ,6 ,axis=1)
print(np.append(var1 ,[[22,33]] ,axis=0))
print(v1)
print(v2)

[[ 1  2]
 [ 3  4]
 [22 33]]
[[1 2]
 [3 4]
 [6 6]]
[[1 2 6]
 [3 4 6]]


# Delete

In [36]:
var = np.array([1,2,3,4,5])
print(var)
de =np.delete(var ,2)
print(de)

[1 2 3 4 5]
[1 2 4 5]
