# Join And Split

In [8]:
import numpy as np 

v1 = np.array([[1,2],[3,4]])
v2= np.array([[4,5],[6,7]])
ar = np.concatenate((v1,v2),axis=1)
ar2 = np.concatenate((v1,v2),axis=0,dtype="float")
print(ar)
print(ar2)

[[1 2 4 5]
 [3 4 6 7]]
[[1. 2.]
 [3. 4.]
 [4. 5.]
 [6. 7.]]


In [15]:
v1 = np.array([[1,2],[3,4]])
v2= np.array([[4,5],[6,7]])
ar = np.stack((v1,v2))
ar2 = np.hstack((v1,v2))
ar3 = np.vstack((v1,v2))
ar4 = np.dstack((v1,v2))
print(ar)
print("horizontal \n " , ar2 )
print("vertical \n" , ar3 )
print("height \n" , ar4 )

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
horizontal 
  [[1 2 4 5]
 [3 4 6 7]]
vertical 
 [[1 2]
 [3 4]
 [4 5]
 [6 7]]
height 
 [[[1 4]
  [2 5]]

 [[3 6]
  [4 7]]]


# SPlits

In [19]:
var = np.array([1,2,4,5,6,7])

print(var)
ar = np.split(var ,3)
print(ar)
print(type(ar))
print(ar[0])

[1 2 4 5 6 7]
[array([1, 2]), array([4, 5]), array([6, 7])]
<class 'list'>
[1 2]


In [26]:
var = np.array([[1,2],[4,5],[6,7]] )

print(var)
ar = np.split(var ,3 , axis=0)
print(ar)
print(type(ar))
print(ar[0])

[[1 2]
 [4 5]
 [6 7]]
[array([[1, 2]]), array([[4, 5]]), array([[6, 7]])]
<class 'list'>
[[1 2]]
