# Matrix Function

Transpose

In [6]:
import numpy as np 
mt = np.matrix([[1,2,3],[4,5,6]])
print(np.transpose(mt))
print()
print(mt.T)
print()
print(np.swapaxes(mt ,1,0))

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


swapeaxes 

In [9]:
mt2 = np.matrix([[1,2],[3,4]])
print(mt2)
print()
print(np.swapaxes(mt2 ,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


Inverse

In [11]:
mt2 = np.matrix([[1,2],[3,4]])
print(mt2.I)
print()
print(np.linalg.inv(mt2))

[[-2.   1. ]
 [ 1.5 -0.5]]

[[-2.   1. ]
 [ 1.5 -0.5]]


Power of Matrix

In [13]:
mt2 = np.matrix([[1,2],[3,4]])
print(mt2)
print()

print(np.linalg.matrix_power(mt2,2))
print()
print(np.linalg.matrix_power(mt2,-2))


[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


Determnants of Matrix

In [15]:
mt2 = np.matrix([[1,2],[3,4]])
print(np.linalg.det(mt2))

-2.0000000000000004
