# Matrix

In [4]:
import numpy as np  
mat = np.matrix([[1,2,3,],[4,5,6]])
var = np.array([[1,2,3,],[4,5,6]])
print(mat)
print(var)
print(type(mat))
print(type(var))


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>
<class 'numpy.ndarray'>


In [16]:
mat1 = np.matrix([[1,2,3,],[4,5,6]])
mat2 = np.matrix([[1,2,3,],[4,5,6]])
print(mat1+mat2)


[[ 2  4  6]
 [ 8 10 12]]


In [18]:
mat1 = np.matrix([[1,2],[4,5]])
mat2 = np.matrix([[1,2],[4,5]])
print(mat1*mat2)
print(mat1.dot(mat2))

[[ 9 12]
 [24 33]]
[[ 9 12]
 [24 33]]
