# Search 

In [8]:
import numpy as np
a =  np.array([1,2,3,4,2,25,6,2,7])

x = np.where(a==2)
x1 =np.where(a%2==0)

print(x)
print(x1)

(array([1, 4, 7], dtype=int64),)
(array([1, 3, 4, 6, 7], dtype=int64),)


Search SOrt araay

In [12]:
a1 =  np.array([1,2,3,4,5,6,7,8])

x1 = np.searchsorted(a1 , 5 ,side="right")
x2 = np.searchsorted(a1 , 5 ,side="left")
print(x1) # give the position where the value can place in array
print(x2) # give the position where the value can place in array

5
4


In [13]:
a1 =  np.array([1,2,3,4,6,7,8])
x1 = np.searchsorted(a1 , [5,6,9] ,side="right")
x2 = np.searchsorted(a1 , 5 ,side="left")

print(x1)

[4 5 7]


# SOrt array

In [16]:
a1 =  np.array([1,12,3,33,4,63,7,8])
c1= np.array(['s','p', 'q','t','b'])
n1 = np.array(['h','a','r','i','s','h'])
print(np.sort(a1))
print(np.sort(c1))
print(np.sort(n1))

[ 1  3  4  7  8 12 33 63]
['b' 'p' 'q' 's' 't']
['a' 'h' 'h' 'i' 'r' 's']


In [17]:
a1 =  np.array([[1,12,3],[33,4,63],[7,8,2]])
print(np.sort(a1))

[[ 1  3 12]
 [ 4 33 63]
 [ 2  7  8]]


# Filter

In [19]:
c1= np.array(['s','p', 'q','t','b'])
   
f = [True , False ,True ,True,False]
new_a = c1[f]
print(new_a)

['s' 'q' 't']
