# Shape

In [4]:
import numpy as np 
var = np.array([[1,2,3],[3,4,3]])

print(var)
print()
print(var.shape)

[[1 2 3]
 [3 4 3]]

(2, 3)


In [8]:
var1 = np.array([[1,2,3,4,5], [2,34,5,6,7]] , ndmin=4)
print(var1)
print(var1.ndim)
print(var1.shape)

[[[[ 1  2  3  4  5]
   [ 2 34  5  6  7]]]]
4
(1, 1, 2, 5)


# Reshape

In [15]:
var =np.array([1,2,2,3,4,4,5,5])
x =var.reshape(4,2)
print(x)
print(x.ndim)
print(x.shape)

[[1 2]
 [2 3]
 [4 4]
 [5 5]]
2
(4, 2)


3D array reshape

In [16]:
var =np.array([1,2,2,3,4,4,5,5])
x =var.reshape(2,2,2)
print(x)
print(x.ndim)
print(x.shape)

[[[1 2]
  [2 3]]

 [[4 4]
  [5 5]]]
3
(2, 2, 2)


In [18]:
var =np.array([1,2,2,3,4,4,5,5])
x =var.reshape(2,2,2)
print(x)
print(x.ndim)
print(x.shape)
x2  = x.reshape(-1)
print(x2.ndim)
print(x2.shape)

[[[1 2]
  [2 3]]

 [[4 4]
  [5 5]]]
3
(2, 2, 2)
1
(8,)
